### ISSUE TITLE
Objectify descriptor elements

### ISSUE THREAD

**Issue by rcernich** [concrt/concreate#57]
I think it would be nice if we defined first level classes for each object type in the configuration.  At minimum, we could use yaml.load() so we can operate on the config as ``foo.key`` as opposed to ``foo['key']``.  I think this would help make the code base more readable and would allow for better organization.

**Comment by dbecvarik** [comment]
I think, that yam.load() support custom loader which can be used to inject custom dictionary type. So instead of many classes we can ask yaml.load() to use our extended dictionary which can support . notation for accessing values via __getattr__, __setattr__. 
It depends if we want to use these classes to provide some functionality or just serve as containers.

**Comment by rcernich** [comment]
One of the reasons I had for doing this, is that I think it might simplify the descriptors, since we would have a base CommonDescriptor, with ImageDescriptor, ModuleDescriptor, and OverridesDescriptor as subclasses (I don't know the exact hierarchy, as ImageDescriptor might extend ModuleDescriptor).  Those would share much of the same code and, I think, make the code base easier to parse.

**Comment by dbecvarik** [comment]
it was already implemented, descriptors is now made of objects and dictionary is wrapped inside
